#!/usr/bin/env python3
"""Write CKPT_OVERRIDES for the f2d sweep on a machine that does not have bellman's /raid.

The sweep driver normally finds each route's checkpoint through the source sweep's run_summary.json,
which records bellman's absolute paths. On another machine those files are absent, so every route
falls through to CKPT_OVERRIDES instead -- this script builds that file from wherever the HL
checkpoints were copied.

For each route it picks the LAST checkpoint of that route's training run, choosing:
  * the numerically largest step (`8000` sorts after `10000` as text -- that bug picks an older one);
  * never a run directory marked INVALID (animals-1076 has one trained before the animal assets
    existed: `..._20260917_234028.INVALID_ran_on_0916_no_animal`);
  * only a checkpoint the loader can actually use: pytorch_model.bin plus .hydra/config.yaml.

    python3 build_ckpt_overrides.py HL_CKPT_ROOT ROUTES_FILE OUT_TSV

Exits non-zero, writing nothing, if any route has no usable checkpoint.
"""
import sys
from pathlib import Path


def last_checkpoint(root: Path, route: str):
    best = None
    for run in root.rglob(f"*{route}_seed_*"):
        if not run.is_dir() or "INVALID" in run.name or not (run / "checkpoints").is_dir():
            continue
        for ck in (run / "checkpoints").iterdir():
            if not ck.name.isdigit():
                continue
            if not ((ck / "pytorch_model.bin").is_file() and (ck / ".hydra" / "config.yaml").is_file()):
                continue
            step = int(ck.name)
            if best is None or step > best[0]:
                best = (step, ck)
    return best


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    root, routes_file, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    routes = [r for r in routes_file.read_text().split() if r]
    rows, missing = [], []
    for r in routes:
        found = last_checkpoint(root, r)
        if found is None:
            missing.append(r)
        else:
            rows.append((r, found[1].resolve(), found[0]))
    if missing:
        sys.exit(f"no usable checkpoint (pytorch_model.bin + .hydra) under {root} for: {', '.join(missing)}")
    out.write_text("# route <TAB> checkpoint, generated by build_ckpt_overrides.py\n"
                   + "".join(f"{r}\t{ck}\n" for r, ck, _ in rows))
    for r, ck, step in rows:
        print(f"  {r:48s} {step:>6d}  {ck}")
    print(f"wrote {out} ({len(rows)} routes)")


if __name__ == "__main__":
    main()
