fail2drive_carla_root: ''
host: localhost
port: 0
streaming_port: 0
x_display_num: 0
traffic_manager_port: 0
traffic_manager_seed: 0
debug: 0
record: ''
timeout: 7200
track: SENSORS
resume: false
checkpoint: ./simulation_results.json
debug_checkpoint: ./live_results.txt
gpu_rank: 1
repetitions: 1
repetition_index: 0
crash_stuck_speed_threshold: 0.1
crash_stuck_steps: 1000000000
crash_stuck_penalty: 0.0
max_episode_steps: 4000
progress_reward_weight: 5.0
