fail2drive_carla_root: ''
host: localhost
port: 12000
streaming_port: 12001
x_display_num: 30
traffic_manager_port: 18000
traffic_manager_seed: 0
debug: 0
record: ''
timeout: 7200.0
track: SENSORS
resume: false
checkpoint: /home/carla/ogbench-carla/leaderboard_runs/b2d_ckpt6000_seed0/records/accident-003.json
debug_checkpoint: /home/carla/ogbench-carla/leaderboard_runs/b2d_ckpt6000_seed0/records/accident-003.live.txt
gpu_rank: 1
repetitions: 1
repetition_index: 0
crash_stuck_speed_threshold: 0.1
crash_stuck_steps: 1000000000
crash_stuck_penalty: -5.0
max_episode_steps: 0
progress_reward_weight: 5.0
terminate_on_infraction: false
